disabled_rules: # rule identifiers to exclude from running
  - colon
  - comma
  - control_statement
  - shorthand_operator
  - large_tuple
  - trailing_whitespace
  - cyclomatic_complexity
  - function_parameter_count
  - multiple_closures_with_trailing_closure
opt_in_rules: # some rules are only opt-in
  # - empty_count
  # Find all the available rules by running:
  # swiftlint rules
included: # paths to include during linting. `--path` is ignored if present.
  - ./
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
  - R.generated.swift

# configurable rules can be customized from this configuration file
# binary rules can set their severity level
force_cast: warning # implicitly
force_try:
  severity: warning # explicitly
# rules that have both warning and error levels, can set just the warning level
# implicitly
line_length: 300
# they can set both implicitly with an array
type_body_length:
  - 500 # warning
  - 1600 # error
#
function_body_length:
  - 80 # warning
  - 300 # error
# or they can set both explicitly
file_length:
  warning: 1500
  error: 1600
# naming rules can set warnings/errors for min_length and max_length
# additionally they can set excluded names
type_name:
  min_length: 2 # only warning
  max_length: # warning and error
    warning: 40
    error: 50
  excluded:
    
# CyclomaticComplexityRule
cyclomatic_complexity:
  - 10
  - 81
identifier_name:
  min_length: 1 # only min_length
  excluded: # excluded via string array

function_parameter_count:
  error: 13

reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit, html, emoji)
