# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NewProject' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'R.swift'
  pod 'SwiftLint'
  pod 'DeviceGuru'
  pod 'ReachabilitySwift'
  pod 'SwiftFormat/CLI'
  pod 'SnapKit', '~> 4.0'
  target 'ImageLoaderTests' do
    inherit! :search_paths
  end
end
