# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NewProject' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'R.swift'
  pod 'SwiftLint'
  pod 'ReachabilitySwift'
  pod 'SwiftFormat/CLI'
  pod 'SnapKit', '~> 4.0'
  pod 'HouJia', :git => 'https://github.com/JeromeTW/HouJia.git', :commit => '0086d20'
  target 'Tests' do
    inherit! :search_paths
  end
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
#      puts "##### target: #{target} #####"
      target.build_configurations.each do |config|
#        puts "##### config: #{config} #####"
        if config.name == 'Test'
          config.build_settings['OTHER_SWIFT_FLAGS'] ||= ['-DDEBUG', '-DTEST']
        else
          config.build_settings['OTHER_SWIFT_FLAGS'] = '-DDEBUG'
        end
      end
    end
end
